### PR TITLE
LPS-74505 Search Results Portlet: unable to view individual results

### PR DESCRIPTION
**Pull request by arboliveira**
Running CI here exceptionally, in order to replicate a CI blocker spotted in my own pull.

Author: @wcao20170619 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-74505

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
This pull request (and all further pull requests in CI) is probably going to fail after 30 minutes due to changes introduced in https://github.com/brianchandotcom/liferay-portal/pull/56301.

The failure is like:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/collaboration/bookmarks
/bookmarks-uad/src/main/java/com/liferay/bookmarks/uad/exporter
/BookmarksEntryUADEntityExporter.java:110: error: method does not override or implement a 
method from a supertype
     [exec] 	@Override
     [exec] 	^
```

First sighting: https://github.com/arboliveira/liferay-portal/pull/436#issuecomment-373976068

@brianchandotcom 
@pei-jung
@pyoo47

**Comment by arboliveira** [comment]
@brianchandotcom @pei-jung @pyoo47 Blocker CI failure replicated as described in https://github.com/brianchandotcom/liferay-portal/pull/56305#issuecomment-373977632. Please verify. Changes in my pull aren't safe to be merged without a full CI run. Thank you!

**Comment by pei-jung** [comment]
Hi @arboliveira, 

I've sent the fix to https://github.com/brianchandotcom/liferay-portal/pull/56306. Thanks!
