### PR TITLE
LPS-99657

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f2890604d...9e8b8bf031

**Comment by brianchandotcom** [comment]
@arboliveira fyi

**Comment by xbrianlee** [comment]
This PR breaks stable job compile on 7.2.x
```
     [exec] > Task :apps:portal-search:portal-search-test-util:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal-7.2.x/modules/apps/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/filter/tags/BaseAssetTagNamesQueryPreFilterContributorTestCase.java:20: error: package com.liferay.portal.search.internal.spi.model.query.contributor does not exist
     [exec] import com.liferay.portal.search.internal.spi.model.query.contributor.AssetTagNamesQueryPreFilterContributor;
     [exec]                                                                      ^
     [exec] /opt/dev/projects/github/liferay-portal-7.2.x/modules/apps/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/filter/tags/BaseAssetTagNamesQueryPreFilterContributorTestCase.java:59: error: cannot find symbol
     [exec]                     new AssetTagNamesQueryPreFilterContributor();
     [exec]                         ^
```
