### PR TITLE
LPD-74515 Fix compilation error

### PR DESCRIPTION
**Pull request by carolmariaabb**
Fix compilation error caused by https://github.com/brianchandotcom/liferay-portal/commit/e636b33398d0fc97772c70b95755ce20fa779ab3

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0df2c7d151...c94623fae4
