### PR TITLE
LPS-190839 revert updating okio

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi Brian,

I found there is a blocker in upstream (not reported by others yet) when we try to add a word file with one-drive(Reproduce step is similar to https://liferay.atlassian.net/browse/LPS-191330), it should be caused by https://github.com/liferay-core-infra/liferay-portal/pull/5048
```
Exception in thread "liferay/background_task-5" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics 
       at okio.Buffer.write(Buffer.kt) 
       at okhttp3.ResponseBody.create(ResponseBody.java:210) 
       at okhttp3.internal.Util.<clinit>(Util.java:62) 
       at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127) 
       at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:475) 
       at com.microsoft.graph.httpcore.HttpClients.custom(HttpClients.java:22) 
       at com.microsoft.graph.httpcore.HttpClients.createDefault(HttpClients.java:37) 
       at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:245) 
       at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204) 
       at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184) 
       at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:306) 
       at com.microsoft.graph.http.CustomRequest.post(CustomRequest.java:106) 
       at com.liferay.document.library.opener.onedrive.web.internal.background.task.UploadOneDriveDocumentBackgroundTaskExecutor._uploadFile(UploadOneDrive
DocumentBackgroundTaskExecutor.java:227) 
       at com.liferay.document.library.opener.onedrive.web.internal.background.task.UploadOneDriveDocumentBackgroundTaskExecutor.execute(UploadOneDriveDocu
mentBackgroundTaskExecutor.java:97) 
       at com.liferay.portal.background.task.internal.SerialBackgroundTaskExecutor.execute(SerialBackgroundTaskExecutor.java:54) 
       at com.liferay.portal.kernel.backgroundtask.DelegatingBackgroundTaskExecutor.execute(DelegatingBackgroundTaskExecutor.java:32) 
       at com.liferay.portal.background.task.internal.ThreadLocalAwareBackgroundTaskExecutor.execute(ThreadLocalAwareBackgroundTaskExecutor.java:63) 
       at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:115) 
       at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:39) 
       at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:25) 
       at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:65) 
       at com.liferay.portal.messaging.internal.ParallelDestination$1.run(ParallelDestination.java:47) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
       at java.lang.Thread.run(Thread.java:750) 
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics cannot be found by com.liferay.document.library.opener.onedrive.web_3.0.45 
       at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:518) 
       at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429) 
       at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) 
       at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:151) 
       at java.lang.ClassLoader.loadClass(ClassLoader.java:351) 
       ... 25 more
```

I am going to revert it for now, and send the PR with updating Okio to core-infra. 
Thanks for checking!

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:reopen

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:reopen
